### PR TITLE
Fix/scheduledmaintenance

### LINKED ISSUE #12: Add support for scheduled maintenance
Statuspage returns "scheduled_maintenances" as a separate array from "incidents" as seen in [this example](https://gist.github.com/ericgriffis/453af8318e1f291e2be3119369e45552). We want to display valid scheduled maintenance in this array using [the same logic as implemented in status jockey](https://github.com/NYULibraries/library.nyu.edu/wiki/Statuspage.io-site-alerts).

### PR DESCRIPTION
**Pull request by laurxnemeth**

### CODE REVIEW

File: js/statuspageApi.js [hunk 1]
```diff
@@ -9,7 +11,40 @@ class StatuspageApi {
...
+    let incidentUpdated;
+    let maintenanceUpdated;
+
+    // if scheduled_maintenances has a relevant hashtag, add to the scheduledMaintenances variable
+    // if not, the chosenIncident is automatically incidents
+    if (
+      this.data.scheduled_maintenances === undefined ||
+      !hashtagRegexp.test(
+        this.data.scheduled_maintenances[0].incident_updates[0].body
+      )
```
Comment (ericgriffis) [inline js/statuspageApi.js]: So this logic in the "if" block could be its own method, something descriptive like `doesScheduledMaintenanceMatchHashtag` and/or it'd be nice to also refactor `hasMatchingHashtag` so that they share the logic that checks against the regexp.

File: js/statuspageApi.js [hunk 2]
```diff
@@ -9,7 +11,40 @@ class StatuspageApi {
   }
 
   lastIncident() {
```
Comment (ericgriffis) [inline js/statuspageApi.js]: Maybe this method should be named something more descriptive like "mostRecentMaintenance" or similar

File: js/statuspageApi.js [hunk 3]
```diff
@@ -9,7 +11,40 @@ class StatuspageApi {
...
+      maintenanceUpdated = scheduledMaintenances.updated_at.slice(0,19)
+
+      // check if they were updated at the same time
+      if (incidentUpdated === maintenanceUpdated) {
+        chosenIncident = incidents;
+      } else {
+        // else, check which one was the most recent
+        incidents.updated_at < scheduledMaintenances.updated_at
+          ? (chosenIncident = scheduledMaintenances)
+          : (chosenIncident = incidents);
```
Comment (ericgriffis) [inline js/statuspageApi.js]: I think everything inside this big if block could be reduced to something like the following pseudocode:
```
if (maintenanceMoreRecentThanIncident())
  chosen = maintenance
else
  chosen = incident
```
And then just add the updated_at logic and variables to that `maintenanceMoreRecentThanIncident` method (feel free to pick another name here).

File: spec/statuspageApi.spec.js [hunk 4]
```diff
@@ -123,8 +148,35 @@ describe('#hasMatchingHashtag', () => {
...
+      firstIncidentsDate = '2020-07-20T09:11:40.438-04:00'
+      firstMaintenanceDate = '2020-07-20T09:11:40.438-04:00'
+      scheduledMaintenanceBody = '#scheduledmaintenance'
+      statuspageApi.data = getMockData();
+    });
+
+    it('should return incidents instead of scheduled maintenance', ()=> {
+      expect(statuspageApi.incidentName()).toEqual('FirstIncident');
+    })
+  })
```
Comment (ericgriffis) [inline spec/statuspageApi.spec.js]: So the describe with the `#` are for each method, so just move these tests into the `#lastIncident` block (remember to rename if you renamed the method itself), but you could also keep them in a separate describe like `describe("when scheduled maintenance present")`

**Review by ericgriffis — CHANGES_REQUESTED** [review]
@laurxnemeth Just trying out this review functionality! We'll see how it goes, I think I added everything we mentioned this morning. Thanks for doing this, again the logic is great, just need to refactor for readability

**Review by ericgriffis — APPROVED** [review]
